name: mlflow-examples-keras_tf_mnist
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.16.0
    - tensorflow==2.4.1 # ONNX training fails
    #- tensorflow==2.3.0 # ONNX training OK
    - onnx==1.8.1
    - onnxmltools==1.7.0
    - onnxruntime==1.7.0
    - keras2onnx==1.7.0
    - Pillow
