name: mlflow-examples-keras_tf_mnist
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.14.0
    #- $HOME/lib/wheels/mlflow-1.12.2.dev0-py3-none-any.whl
    - tensorflow==2.4.0 # ONNX training fails
    #- tensorflow==2.3.0 # ONNX training OK
    - onnx==1.8.0
    - onnxmltools==1.7.0
    - onnxruntime==1.6.0
    - keras2onnx==1.7.0
    - Pillow
