name: mlflow-examples-catboost
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow>=1.30.0
    - catboost==1.1.1
    - scikit-learn==1.2.1
    - onnx==1.13.0
    - onnxruntime==1.13.1
    - onnxmltools==1.11.1
