name: mlflow-examples-catboost
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.16.0
    - catboost==0.24.4
    - scikit-learn==0.20.2
    - pyarrow=>1.0.0
    - onnx==1.7.0
    - onnxmltools==1.7.0
    - onnxruntime==1.4.0
