name: mlflow-examples-catboost
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow>=1.30.0
    - catboost==0.25.1
    - scikit-learn==0.24.2
    - pyarrow>=1.0.0
    - onnx==1.9.0
    - onnxmltools==1.7.0
    - onnxruntime==1.7.0
