name: mlflow-examples-sparkml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=19.0.3
  - pip:
    - mlflow>=1.17.0
    - mleap==0.17.0
    - pyspark==3.3.1
    - pyarrow>=1.0.0
    - onnx==1.9.0
    - onnxmltools==1.7.0
    - onnxruntime==1.7.0
