name: mlflow-examples-sparkml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow>=2.2.2
    - mleap==0.21.1
    - pyspark==3.4.0
    - pyarrow>=1.0.0
    - onnx==1.13.1
    - onnxruntime==1.14.1
    - onnxmltools==1.11.2
