name: mlflow-examples-sklearn
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.14.0
    - scikit-learn==0.20.2
    - matplotlib==3.2.1
    - pyarrow==0.17
    - onnx==1.8.0
    - onnxmltools==1.7.0
    - onnxruntime==1.6.0
