name: mlflow-examples-sklearn
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow>=2.4.2
    - scikit-learn
    - matplotlib
    - onnx==1.14.0
    - onnxruntime==1.15.1
    - skl2onnx==1.14.1
    - pyspark==3.3.1
    - shortuuid

    #- onnx==1.13.1
    #- onnxruntime==1.14.1
    #- onnxmltools==1.11.2
